#####################################################################
#                                                                   #
# Script:  compose.yaml                                             #
#                                                                   #
# Purpose: Docker compose definition for exim-db                    #
#                                                                   #
# Date:    11th May 2025                                            #
#                                                                   #
# Author:  datr.tech admin <admin@datr.tech>                        #
#                                                                   #
#####################################################################

services:
  exim-db:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EXIM_DB_AUTHOR: ${EXIM_DB_AUTHOR}
        EXIM_DB_SQL_FILE: ${EXIM_DB_SQL_FILE}
        EXIM_DB_SQL_PATH: ${EXIM_DB_SQL_PATH}
    container_name: ${EXIM_DB_CONTAINER}
    environment:
      MARIADB_DATABASE: ${EXIM_DB_NAME}
      MARIADB_ROOT_PASSWORD: ${EXIM_DB_USER_ROOT_PASS}
      MARIADB_ROOT_USER: ${EXIM_DB_USER_ROOT}
      MARIADB_USERNAME: ${EXIM_DB_USER_STD}
    healthcheck:
      interval: 10s
      start_period: 30s
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      timeout: 5s
    networks:
      - ${EXIM_NETWORK}
    ports:
      - ${EXIM_DB_PORT}:${EXIM_DB_PORT}
    restart: unless-stopped
    volumes:
      - type: volume
        source: ${EXIM_DB_SOCKET_VOLUME}
        target: ${EXIM_DB_SOCKET_VOLUME_TARGET}
networks:
  exim-network:
    attachable: true
    driver: bridge
    name: ${EXIM_NETWORK}
volumes:
  exim-db-socket-volume:
    driver: local
    name: ${EXIM_DB_SOCKET_VOLUME}
