#####################################################################
#                                                                   #
# Script:  compose.yaml                                             #
#                                                                   #
# Purpose: Docker compose definition for exim-db                    #
#                                                                   #
# Date:    11th May 2025                                            #
#                                                                   #
# Author:  datr.tech admin <admin@datr.tech>                        #
#                                                                   #
#####################################################################

services:
  exim-db:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EXIM_DB_AUTHOR: ${EXIM_DB_AUTHOR}
        EXIM_DB_SQL_FILE: ${EXIM_DB_SQL_FILE}
        EXIM_DB_SQL_PATH: ${EXIM_DB_SQL_PATH}
    container_name: exim-db
    environment:
      MARIADB_DATABASE: ${EXIM_DB_NAME}
      MARIADB_ROOT_PASSWORD: ${EXIM_DB_ROOT_PASS}
      MARIADB_ROOT_USER: ${EXIM_DB_ROOT_USER}
      MARIADB_USERNAME: ${EXIM_DB_USER}
    healthcheck:
      interval: 10s
      start_period: 30s
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      timeout: 5s
    networks:
      - exim-network
    ports:
      - ${EXIM_DB_PORT}:${EXIM_DB_PORT}
    restart:
      unless-stopped
      #volumes:
      #- ./sql/*.sh:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/mysql
networks:
  exim-network:
    driver: bridge
